plugins {
    id 'com.android.application'
}

android {
    namespace 'com.taskearn.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.taskearn.app'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }

    signingConfigs {
        release {
            def storeFilePath = System.getenv("TASK_EARN_KEYSTORE")
            if (storeFilePath) {
                storeFile file(storeFilePath)
                storePassword System.getenv("TASK_EARN_STORE_PASSWORD")
                keyAlias System.getenv("TASK_EARN_KEY_ALIAS")
                keyPassword System.getenv("TASK_EARN_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            debuggable false
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'com.google.android.gms:play-services-ads:24.6.0'
}
